[package]
name = "telchar"
version = "2026.8.1"
edition = "2024"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
nix-worker-protocol = { path = "../nix-worker-protocol" }
serde.workspace = true
serde_json.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-appender-tracing.workspace = true
tokio.workspace = true
rustix = { version = "1.1.4", features = [
  "event",
  "fs",
  "net",
  "process",
  "time",
] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
sha2 = "0.10"
hmac = "0.12"
base64 = "0.22"
postgres = "0.19"
r2d2 = "0.8"
r2d2_postgres = "0.18"
tokio-postgres-rustls = "0.14"
rustls-native-certs = "0.8"
rustls-pemfile = "2"
url = "2"
toml = "0.8"
reqwest.workspace = true
otlp-http-client.workspace = true
rustls.workspace = true
tungstenite.workspace = true
jsonwebtoken = "9.3.1"
tempfile = "3.27.0"
signal-hook = "0.3"
libc = "0.2"

[dev-dependencies]
opentelemetry-proto.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
