[package]
name = "telchar-nomad-worker"
version = "2026.9.0"
edition = "2024"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
telchar = { path = "../telchar" }
telchar-telemetry = { path = "../telchar-telemetry" }
tracing.workspace = true
opentelemetry.workspace = true
nix-worker-protocol = { path = "../nix-worker-protocol" }
base64 = "0.22"
reqwest.workspace = true
tungstenite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
hmac = "0.12"
url = "2"

[dev-dependencies]
opentelemetry-proto.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
